config/routes.rb
Rails.application.routes.draw do


  get 'static_pages/address/:id' => 'static_pages#address', as: :view_address
  get 'static_pages/ticket/:id' => 'static_pages#ticket', as: :view_ticket
  get 'static_pages/timing/:id' => 'static_pages#timing', as: :view_timing
  get 'static_pages/details/:id' => 'static_pages#details', as: :view_details
  get 'static_pages/search' => 'static_pages#search', as: :view_search
  get 'static_pages/photos/:id' => 'static_pages#photos', as: :view_photos
  get 'static_pages/rating/:id' => 'static_pages#rating', as: :view_ratings
  root 'static_pages#new'
  devise_for :users, controllers: {
           :sessions => "users/sessions",
           :registrations => "users/registrations" }

  
	post 'tickets/search_by', to: 'tickets#search_by'
	post 'timings/search_by', to: 'timings#search_by'
  post 'pictures/search_by', to: 'pictures#search_by'
  
  resources :pages
  resources :pictures
  resources :timings
  resources :tickets
  resources :products
  resources :places
  resources :addresses
  resources :states
  resources :static_pages

  #get 'admin_homes/home' => 'admin_homes#home', as: :adminhome
  # authenticated :user do
  #   root to: 'admin_homes#home'
  # end

  #root :to => 'home#static_page'
 #post 'admin_homes/home', to: 'admin_homes#home', as: :homeeeee
  
  #post 'admin_homes/home' 
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    user ||= User.new
    
        if user.user?
            can [:create],[Place]
        elsif user.admin?
            can :manage, :all
            can :access, :all
            # can :manage, Home
        end

    # if user.has_role? :admin
    #     #can :manage, :all
    #     can :access, :all
    # elsif user.has_role? :user
    #   #can [:index, :read, :update, :destroy], :users, :user_id => user.id
    #   cannot :access, :users
    # #else
    #     #can :read, :all
    # end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ApplicationRecord
	resourcify
	belongs_to :state
	belongs_to :place
	#validates :area_name, :road_name, :landmark, :city_name, :remarks, :pincode, presence: true

	#def full_address
		#{}"#{area_name}, #{road_name}, #{landmark}, #{city_name}, #{remarks}, #{pincode}"
	#end
	geocoded_by :address 
	geocoded_by :full_address

	after_validation :geocode
	  def full_address    
	  	"#{area_name}, #{road_name}, #{landmark}, #{city_name}, #{pincode}"
	  end
	
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/picture.rb
class Picture < ApplicationRecord
	resourcify
	mount_uploader :image, ImageUploader
  belongs_to :place
  def self.search(search)
  @place = Place.where('lower(place_name) ILIKE ?', "%#{search.downcase}%")
  	if search == ""
  		@pictures = Picture.all
		elsif @place.nil?
  		@pictures = Picture.where(place_id: 0)
  	else
   		@pictures = Picture.where(place_id: @place.ids)
   	end

  end
end

app/models/place.rb
class Place < ApplicationRecord
	resourcify
	ratyrate_rateable "place_name"
  has_one :address, dependent: :destroy
  has_one :ticket,  dependent: :destroy
  has_many :timings, dependent: :destroy
  has_many :pictures, dependent: :destroy
  accepts_nested_attributes_for :address
  validates :place_name, :place_type, :place_details, :phone_number, presence: true
  enum status:[:pending,:confirmed]

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true

validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },

          :allow_nil => true

scopify
end

app/models/state.rb
class State < ApplicationRecord
	resourcify
	has_many :addresses, dependent: :destroy
	validates :state_name, presence: true, uniqueness: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  resourcify
  belongs_to :place
  def self.search(search)
  	@place = Place.where('lower(place_name) ILIKE ?', "%#{search.downcase}%")
  	if search == ""
  		@tickets = Ticket.all
		elsif @place.nil?
  		@tickets = Ticket.where(place_id: 0)		
  	else
   		@tickets = Ticket.where(place_id: @place.ids)
   	end
  end
end

app/models/timing.rb
class Timing < ApplicationRecord
  resourcify
  belongs_to :place
  def self.search(search)
  	@place = Place.where('lower(place_name) ILIKE ?', "%#{search.downcase}%")
  	if search == ""
  		@timings = Timing.all
		elsif @place.nil?
  		@timings = Timing.where(place_id: 0)		
  	else
   		@timings = Timing.where(place_id: @place.ids)
   	end
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  ratyrate_rater
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 	after_create :assign_default_rolt_to_user
  has_one :authentication_token, dependent: :destroy

 	def assign_default_rolt_to_user
 		add_role(:user)
 	end

	def admin?
	  has_role?(:admin)
	end

	def user?
	  has_role?(:user)
	end 

	def generate_authentication_token
    token = SecureRandom.hex(16)
    user_auth = AuthenticationToken.find_by(user_id: id)
    if user_auth.present?
      user_auth.update_attributes(auth_token: token, user_id: id)
    else
      user_auth = AuthenticationToken.create!(auth_token: token, user_id: id)
    end
    binding.pry
    user_auth
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'staticpagelayout'
  def new
    if user_signed_in?
      if current_user.has_role? :admin
        # redirect_to new_page_path
			end
    end
  end
  
  def search
    @search= params[:search_area]
      @addresses = Address.where("lower(area_name) ILIKE ?", "%#{@search}%" )
      @places=Array.new
      @addresses.each do |address|
        @places<<address.place
      end
    
  end

  def ticket
  	@place_id=params[:id]
  	@place=Place.find(@place_id)
  	@tickets  = Ticket.where(place_id: @place_id).order("ticket_type ASC")		
  end

  def address
  	@place_id=params[:id]
  	@place=Place.find(@place_id)
  	@addresses  = Address.where(place_id: @place_id)
  end

  def timing
  	@place_id=params[:id]
  	@place=Place.find(@place_id)
  	@timings  = Timing.where(place_id: @place_id)
  end

  def details
  	@place_id=params[:id]
  	@place=Place.find(@place_id)	
  end

  def photos
    @place_id=params[:id]
    @place=Place.find(@place_id)
    @pictures  = Picture.where(place_id: @place_id)
  end

  def index
  	search=params[:search]
  	@places = Place.where('lower(place_name) ILIKE ?', "%#{search}%")
 	end

  def rating
    @place = Place.find(params[:id])
  end

  private
    def place_params
      params.require(:place).permit(:place_name, :place_type, :place_details, :phone_number, :search_area)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/timings_helper.rb
module TimingsHelper
end

app/views/static_pages/address.html.erb
<div class="topnav">
  <a class="active" <%= link_to "Ticket", view_ticket_path %></a>
  <a <%= link_to "Address", view_address_path %></a>
  <a <%= link_to "Timing", view_timing_path %></a>
  <a <%= link_to "Details", view_details_path  %></a>
  <a <%= link_to "Photos", view_photos_path  %></a>
  <% if user_signed_in? %>
    <a <%= link_to "Ratings", view_ratings_path  %></a>
  <%end%>
  <div class="search-container">
    <%= form_tag(view_search_path, method: :get) do %>
      <%= text_field_tag :search_area, params[:search_area], placeholder: 'Search area wise' %>
      <button type="submit"><i class="fa fa-search"></i></button>
    <% end %>
  </div>
</div>
<br>
<div class="panel panel-default">
  <div class="panel-body">
    <h3><b><%= @place.place_name %> address </b></h3>
    <hr>
    <span class="glyphicon glyphicon-map-marker"></span>
      <% @addresses.each do |address| %>
        <%= address.area_name %> , 
        <%= address.road_name %> ,
        <%= address.landmark%> ,
        <%= address.remarks%> ,
        <%= address.city_name%> ,
        <%= address.state.state_name%> ,
        <%= address.pincode%>
      <%end%>
  </div>
</div>
  
<div id="main-container" class="container">
  <%= yield %>
</div>

app/views/static_pages/details.html.erb
 <div class="topnav">
    <a class="active" <%= link_to "Ticket", view_ticket_path %></a>
    <a <%= link_to "Address", view_address_path %></a>
    <a <%= link_to "Timing", view_timing_path %></a>
    <a <%= link_to "Details", view_details_path  %></a>
    <a <%= link_to "Photos", view_photos_path  %></a>
    <% if user_signed_in? %>
    <a <%= link_to "Ratings", view_ratings_path  %></a>
    <%end%>
      <div class="search-container">
        <%= form_tag(view_search_path, method: :get) do %>
          <%= text_field_tag :search_area, params[:search_area],placeholder: 'Search area wise' %>
          <button type="submit"><i class="fa fa-search"></i></button>
        <% end %>
      </div>
    </div>
  <br>
<div class="panel panel-default">
  <div class="panel-body">
    <h3><b><%= @place.place_name %> details </b></h3>
    <hr>
      <ul class="b">
        <p align="justify">
        <li>
          <%= @place.place_type %>,
         <%= @place.place_details %>
         </li>
       </p>
      </ul>
  </div>
</div>
  

<div id="main-container" class="container">
  <%= yield %>
</div>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Picnic Info</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-top navbar-fixed-top">
    <div class="container-fluid">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><b>Picnic Info</b></a>
        </div>
      <div>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <% if user_signed_in? %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %>  <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit profile",edit_user_registration_path %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                  </ul>
          <% else %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Login  <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Sign up",new_user_registration_path %></li>
                <li><%= link_to "Login", new_user_session_path %></li>
              </ul>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
  <br>
  <h2>Place List</h2>
  <table class="table table-striped table-bordered table-hover">
    <tbody>
      <% @places.each do |place| %>
        <tr>
          <td class="col-md-2"><%= place.place_name %></td>
          <td><%= link_to 'View More', view_ticket_path(place), class: "btn btn-info"%></td>
        </tr>
      <%end%>
    </tbody>
  </table>

<div id="main-container" class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/static_pages/new.html.erb
<center>
<h2>Enter the place name </h2>
<br>
<%= form_tag(static_pages_path, method: :get) do %>
  <%= text_field_tag :search, params[:search],placeholder: 'Search...' %>
  <%= submit_tag 'Search', name: nil %>
<% end %>
</center>

app/views/static_pages/photos.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" ></script>

<div class="topnav">
  <a class="active" <%= link_to "Ticket", view_ticket_path %></a>
  <a <%= link_to "Address", view_address_path %></a>
  <a <%= link_to "Timing", view_timing_path %></a>
  <a <%= link_to "Details", view_details_path  %></a>
  <a <%= link_to "Photos", view_photos_path  %></a>
  <% if user_signed_in? %>
    <a <%= link_to "Ratings", view_ratings_path  %></a>
    <%end%>
  <div class="search-container">
    <%= form_tag(view_search_path, method: :get) do %>
      <%= text_field_tag :search_area, params[:search_area], placeholder: 'Search area wise' %>
      <button type="submit"><i class="fa fa-search"></i></button>
    <% end %>
  </div>
</div>
<br>
<h3><b><%= @place.place_name %>'s Photos</b></h3>
<hr>
<div class="container"> 
  <div class="row">
    <% @pictures.each do |picture| %>
      <div class="col-md-3 col-sm-4 col-2">          
        <%= image_tag picture.image_url ,:size => "260x180" %>
      </div>
    <% end %>
  </div>  
</div>

<div id="main-container" class="container">
  <%= yield %>
</div>

app/views/static_pages/rating.html.erb
<h2><%= @place.place_name %></h2>
<% if user_signed_in? %>
  <%= rating_for @place, "place_name" %>
<%end %>

app/views/static_pages/search.html.erb
<%= flash_messages %>
<div class="topnav">
      <div class="search-container">
        <%= form_tag(view_search_path, method: :get) do %>
          <%= text_field_tag :search_area, params[:search_area], placeholder: 'Search area wise' %>
          <button type="submit"><i class="fa fa-search"></i></button>
        <% end %>
      </div>
    </div>
  <br>

<h2>Place List</h2>
<div class="product-block">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th class="col-md-2">Place name</th>
      <th class="col-md-2">Phone number</th>
      <th class="col-md-2">Area Name</th>
      <th class="col-md-2">Road Name</th>
      <th class="col-md-2">Landmark</th>
      <th class="col-md-2">City Name</th>
      <th class="col-md-2">Pincode</th>
      <th class="col-md-2">State</th>
      </tr>
    </tr>
  </thead>
  <tbody>
    <% @places.each do |place| %>

      <tr>
        <td class="col-md-2"><%= place.place_name %></td>
        <td class="col-md-2"><%= place.phone_number %></td>
        <td class="col-md-2"><%= place.address.area_name  %></td>
        <td class="col-md-2"><%= place.address.road_name  %></td>
        <td class="col-md-2"><%= place.address.landmark  %></td>
        <td class="col-md-2"><%= place.address.city_name  %></td>
        <td class="col-md-2"><%= place.address.pincode  %></td>
        <td class="col-md-2"><%= place.address.state.state_name  %></td>
     
      </tr>
    <% end %> 
  </tbody>
</table>

app/views/static_pages/ticket.html.erb
<div class="topnav">
  <a class="active" <%= link_to "Ticket", view_ticket_path %></a>
  <a <%= link_to "Address", view_address_path %></a>
  <a <%= link_to "Timing", view_timing_path %></a>
  <a <%= link_to "Details", view_details_path  %></a>
  <a <%= link_to "Photos", view_photos_path  %></a>
  <% if user_signed_in? %>
    <a <%= link_to "Ratings", view_ratings_path  %></a>
  <%end%>
  <div class="search-container">
    <%= form_tag(view_search_path, method: :get) do %>
      <%= text_field_tag :search_area, params[:search_area], placeholder: 'Search area wise' %>
      <button type="submit"><i class="fa fa-search"></i></button>
    <% end %>
  </div>
</div>
<br>
<div class="panel panel-default">
  <div class="panel-body">
    <h3><b><%= @place.place_name %> Tickets </b></h3>
    <hr>
    <table>
      <tbody>
        <% @tickets.each do |ticket| %>
          <ul class="b">
            <li><%= ticket.ticket_price %>  <%= ticket.ticket_type %></li>
          </ul>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

<div id="main-container" class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/static_pages/timing.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
 <div class="topnav">
    <a class="active" <%= link_to "Ticket", view_ticket_path %></a>
    <a <%= link_to "Address", view_address_path %></a>
    <a <%= link_to "Timing", view_timing_path %></a>
    <a <%= link_to "Details", view_details_path  %></a>
    <a <%= link_to "Photos", view_photos_path  %></a>
    <% if user_signed_in? %>
    <a <%= link_to "Ratings", view_ratings_path  %></a>
    <%end%>
      <div class="search-container">
        <%= form_tag(view_search_path, method: :get) do %>
          <%= text_field_tag :search_area, params[:search_area] , placeholder: 'Search area wise'%>
          <button type="submit"><i class="fa fa-search"></i></button>
        <% end %>
      </div>
    </div>
  <br>
<div class="panel panel-default">
  <div class="panel-body">
    <h3><b><%= @place.place_name %> timing </b> </h3>
    <hr> <span class="glyphicon glyphicon-time"></span> Hours:
    <br>
    <% days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"] %>
    <% days=days.rotate(days.index(Time.now.strftime("%A"))) %>
    <%7.times do |i|%>
      <%count=days[i]%>
      <% @ticket=Timing.find_by(day: count)%>
      <%= days[i]%>
      <%= @ticket.start_time.strftime("%I:%M %p") %>
      <%= @ticket.end_time.strftime("%I:%M %p") %>
      <br>
    <%end%>
  </div>
</div>

<div id="main-container" class="container">
  <%= yield %>
</div>

</body>
</html>