config/routes.rb
Rails.application.routes.draw do


  get 'static_pages/address/:id' => 'static_pages#address', as: :view_address
  get 'static_pages/ticket/:id' => 'static_pages#ticket', as: :view_ticket
  get 'static_pages/timing/:id' => 'static_pages#timing', as: :view_timing
  get 'static_pages/details/:id' => 'static_pages#details', as: :view_details
  get 'static_pages/search' => 'static_pages#search', as: :view_search
  get 'static_pages/photos/:id' => 'static_pages#photos', as: :view_photos
  get 'static_pages/rating/:id' => 'static_pages#rating', as: :view_ratings
  root 'static_pages#new'
  devise_for :users, controllers: {
           :sessions => "users/sessions",
           :registrations => "users/registrations" }

  
	post 'tickets/search_by', to: 'tickets#search_by'
	post 'timings/search_by', to: 'timings#search_by'
  post 'pictures/search_by', to: 'pictures#search_by'
  
  resources :pages
  resources :pictures
  resources :timings
  resources :tickets
  resources :products
  resources :places
  resources :addresses
  resources :states
  resources :static_pages

  #get 'admin_homes/home' => 'admin_homes#home', as: :adminhome
  # authenticated :user do
  #   root to: 'admin_homes#home'
  # end

  #root :to => 'home#static_page'
 #post 'admin_homes/home', to: 'admin_homes#home', as: :homeeeee
  
  #post 'admin_homes/home' 
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  resourcify
  belongs_to :place
  def self.search(search)
  	@place = Place.where('lower(place_name) ILIKE ?', "%#{search.downcase}%")
  	if search == ""
  		@tickets = Ticket.all
		elsif @place.nil?
  		@tickets = Ticket.where(place_id: 0)		
  	else
   		@tickets = Ticket.where(place_id: @place.ids)
   	end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: [:index, :show]
  layout 'adminlayout'
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json.
  def index
    @tickets = Ticket.all
  end

  def search_by 
    @tickets = Ticket.search(params[:search]) 
    render 'index'
  end
=begin
  if params[:search]==nil
    @tickets=Ticket.all
  else
    @places = Place.search(params[:search])
  =end
=end  # GET /tickets/1

  def show
  end

  # GET /tickets/1.json
  # GET /tickets/new
  
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:ticket_type, :ticket_price, :place_id, :search)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
      <div class="form-group col-md-4">
      <%= form.label :place_name %><br>
       <% place_arr=Place.all.map{|i| [i.place_name]} %>
      <%= form.collection_select :place_id, Place.order(:id), :id,:place_name, class: "form-control" %>
      </div>
    </div>

  <div class="row">
      <div class="form-group col-md-4">
    <%= form.label :ticket_type %>
    <%= form.select :ticket_type, {per_person_for_Adult: " per person for Adult",
          per_child_for_Children: "per child for Children",
          per_person_Free_entry_for_Senior_Citizen_or_Children_below_5_years: "per person free entry for Senior Citizen or Children below 5 years", 
          per_person_for_Educational_Trip: "per person for Educational trip", 
          per_person_for_Monthly_Pass: "per person for Monthly Pass"} %>
   
  </div>
  </div>

  <div class="row">
      <div class="form-group col-md-4">
    <%= form.label :ticket_price %>
    <%= form.text_field :ticket_price, id: :ticket_ticket_price , class: "form-control"%>
  </div>
  </div>

  <div class="actions">
    <%= form.submit 'Create', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket, class: "btn btn-warning" %> |
<%= link_to 'Back', tickets_path , class: "btn btn-default"%>

app/views/tickets/index.html.erb
<h2>Tickets List</h2>
<%= form_tag(tickets_search_by_path, method: :post) do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag 'Search', name: nil %>
<% end %>

<div class="product-block">
  <table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th class="col-md-2">Ticket type</th>
      <th class="col-md-2">Ticket price</th>
      <th class="col-md-2">Place Name</th>
      <th class="col-md-4"colspan="3"> Options</th>
    </tr>
  </thead>

<tbody>
  
   <% @tickets.each do |ticket| %>
      <tr>
        <td class="col-md-2"><%= ticket.ticket_type %></td>
        <td class="col-md-2"><%= ticket.ticket_price %></td>
        <td class="col-md-2"><%= ticket.place.place_name %></td>
        <td><%= link_to 'Show', ticket, class: "btn btn-info"%></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket), class: "btn  btn-warning" %></td>
        <td><%= link_to 'Destroy', ticket_path(ticket), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
      <%end%>
  </tbody>
</table>
<br>
<%= link_to 'New Ticket', new_ticket_path , class: "btn btn-primary" %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path , class: "btn btn-default"%>

app/views/tickets/show.html.erb
<%= flash_messages %>

<p>
  <strong>Place_name:</strong>
  <%= @ticket.place.place_name %>
</p>
<p>
  <strong>Ticket type:</strong>
  <%= @ticket.ticket_type %>
</p>

<p>
  <strong>Ticket price:</strong>
  <%= @ticket.ticket_price %>
</p>



<%= link_to 'Edit', edit_ticket_path(@ticket) , class: "btn btn-warning" %> |
<%= link_to 'Back', tickets_path , class: "btn btn-default"%>