config/routes.rb
Rails.application.routes.draw do


  get 'static_pages/address/:id' => 'static_pages#address', as: :view_address
  get 'static_pages/ticket/:id' => 'static_pages#ticket', as: :view_ticket
  get 'static_pages/timing/:id' => 'static_pages#timing', as: :view_timing
  get 'static_pages/details/:id' => 'static_pages#details', as: :view_details
  get 'static_pages/search' => 'static_pages#search', as: :view_search
  get 'static_pages/photos/:id' => 'static_pages#photos', as: :view_photos
  get 'static_pages/rating/:id' => 'static_pages#rating', as: :view_ratings
  root 'static_pages#new'
  devise_for :users, controllers: {
           :sessions => "users/sessions",
           :registrations => "users/registrations" }

  
	post 'tickets/search_by', to: 'tickets#search_by'
	post 'timings/search_by', to: 'timings#search_by'
  post 'pictures/search_by', to: 'pictures#search_by'
  
  resources :pages
  resources :pictures
  resources :timings
  resources :tickets
  resources :products
  resources :places
  resources :addresses
  resources :states
  resources :static_pages

  #get 'admin_homes/home' => 'admin_homes#home', as: :adminhome
  # authenticated :user do
  #   root to: 'admin_homes#home'
  # end

  #root :to => 'home#static_page'
 #post 'admin_homes/home', to: 'admin_homes#home', as: :homeeeee
  
  #post 'admin_homes/home' 
end

app/models/picture.rb
class Picture < ApplicationRecord
	resourcify
	mount_uploader :image, ImageUploader
  belongs_to :place
  def self.search(search)
  @place = Place.where('lower(place_name) ILIKE ?', "%#{search.downcase}%")
  	if search == ""
  		@pictures = Picture.all
		elsif @place.nil?
  		@pictures = Picture.where(place_id: 0)
  	else
   		@pictures = Picture.where(place_id: @place.ids)
   	end

  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: [:index, :show]
  layout 'adminlayout'
 before_action :set_picture, only: [:show, :edit, :update, :destroy]
 
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  def search_by 
    @pictures = Picture.search(params[:search])   
    render 'index'
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:title, :image, :place_id, :search)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
      <div class="form-group col-md-4">
      <%= form.label :place_name %><br>
       <% place_arr=Place.all.map{|i| [i.place_name]} %>
      <%= form.collection_select :place_id, Place.order(:id), :id,:place_name, class: "form-control" %>
      </div>
    </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :picture_title %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :picture_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<head>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" ></script>
</head>
<body>
<h2>Picture List</h2>
<%= form_tag(pictures_search_by_path, method: :post) do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag 'Search', name: nil %>
<% end %>
<p id="notice"><%= notice %></p>



<h1>Pictures</h1>
  <div class="container"> 
    <div class="row">
      <% @pictures.each do |picture| %>
        <div class="col-md-3 col-sm-4 col-2">          
          <%= image_tag picture.image_url ,:size => "260x180" %><br>
          <%= link_to 'Show', picture , class: "btn btn-info"%>
          <%= link_to 'Edit', edit_picture_path(picture), class: "btn  btn-warning" %>
          <%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%>
        </div>
      <% end %>
    </div>  
  </div>
<br>
<%= link_to 'New Picture', new_picture_path , class: "btn btn-primary" %>
</body>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @picture.image_url , :size => "260x180" %>
</p>

<p>
  <strong>Place:</strong>

  <%= @picture.place.place_name %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture), class: "btn btn-warning" %> |
<%= link_to 'Back', pictures_path, class: "btn btn-default" %>