config/routes.rb
Rails.application.routes.draw do


  get 'static_pages/address/:id' => 'static_pages#address', as: :view_address
  get 'static_pages/ticket/:id' => 'static_pages#ticket', as: :view_ticket
  get 'static_pages/timing/:id' => 'static_pages#timing', as: :view_timing
  get 'static_pages/details/:id' => 'static_pages#details', as: :view_details
  get 'static_pages/search' => 'static_pages#search', as: :view_search
  get 'static_pages/photos/:id' => 'static_pages#photos', as: :view_photos
  get 'static_pages/rating/:id' => 'static_pages#rating', as: :view_ratings
  root 'static_pages#new'
  devise_for :users, controllers: {
           :sessions => "users/sessions",
           :registrations => "users/registrations" }

  
	post 'tickets/search_by', to: 'tickets#search_by'
	post 'timings/search_by', to: 'timings#search_by'
  post 'pictures/search_by', to: 'pictures#search_by'
  
  resources :pages
  resources :pictures
  resources :timings
  resources :tickets
  resources :products
  resources :places
  resources :addresses
  resources :states
  resources :static_pages

  #get 'admin_homes/home' => 'admin_homes#home', as: :adminhome
  # authenticated :user do
  #   root to: 'admin_homes#home'
  # end

  #root :to => 'home#static_page'
 #post 'admin_homes/home', to: 'admin_homes#home', as: :homeeeee
  
  #post 'admin_homes/home' 
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    user ||= User.new
    
        if user.user?
            can [:create],[Place]
        elsif user.admin?
            can :manage, :all
            can :access, :all
            # can :manage, Home
        end

    # if user.has_role? :admin
    #     #can :manage, :all
    #     can :access, :all
    # elsif user.has_role? :user
    #   #can [:index, :read, :update, :destroy], :users, :user_id => user.id
    #   cannot :access, :users
    # #else
    #     #can :read, :all
    # end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ApplicationRecord
	resourcify
	belongs_to :state
	belongs_to :place
	#validates :area_name, :road_name, :landmark, :city_name, :remarks, :pincode, presence: true

	#def full_address
		#{}"#{area_name}, #{road_name}, #{landmark}, #{city_name}, #{remarks}, #{pincode}"
	#end
	geocoded_by :address 
	geocoded_by :full_address

	after_validation :geocode
	  def full_address    
	  	"#{area_name}, #{road_name}, #{landmark}, #{city_name}, #{pincode}"
	  end
	
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/picture.rb
class Picture < ApplicationRecord
	resourcify
	mount_uploader :image, ImageUploader
  belongs_to :place
  def self.search(search)
  @place = Place.where('lower(place_name) ILIKE ?', "%#{search.downcase}%")
  	if search == ""
  		@pictures = Picture.all
		elsif @place.nil?
  		@pictures = Picture.where(place_id: 0)
  	else
   		@pictures = Picture.where(place_id: @place.ids)
   	end

  end
end

app/models/place.rb
class Place < ApplicationRecord
	resourcify
	ratyrate_rateable "place_name"
  has_one :address, dependent: :destroy
  has_one :ticket,  dependent: :destroy
  has_many :timings, dependent: :destroy
  has_many :pictures, dependent: :destroy
  accepts_nested_attributes_for :address
  validates :place_name, :place_type, :place_details, :phone_number, presence: true
  enum status:[:pending,:confirmed]

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true

validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },

          :allow_nil => true

scopify
end

app/models/state.rb
class State < ApplicationRecord
	resourcify
	has_many :addresses, dependent: :destroy
	validates :state_name, presence: true, uniqueness: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  resourcify
  belongs_to :place
  def self.search(search)
  	@place = Place.where('lower(place_name) ILIKE ?', "%#{search.downcase}%")
  	if search == ""
  		@tickets = Ticket.all
		elsif @place.nil?
  		@tickets = Ticket.where(place_id: 0)		
  	else
   		@tickets = Ticket.where(place_id: @place.ids)
   	end
  end
end

app/models/timing.rb
class Timing < ApplicationRecord
  resourcify
  belongs_to :place
  def self.search(search)
  	@place = Place.where('lower(place_name) ILIKE ?', "%#{search.downcase}%")
  	if search == ""
  		@timings = Timing.all
		elsif @place.nil?
  		@timings = Timing.where(place_id: 0)		
  	else
   		@timings = Timing.where(place_id: @place.ids)
   	end
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  ratyrate_rater
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 	after_create :assign_default_rolt_to_user
  has_one :authentication_token, dependent: :destroy

 	def assign_default_rolt_to_user
 		add_role(:user)
 	end

	def admin?
	  has_role?(:admin)
	end

	def user?
	  has_role?(:user)
	end 

	def generate_authentication_token
    token = SecureRandom.hex(16)
    user_auth = AuthenticationToken.find_by(user_id: id)
    if user_auth.present?
      user_auth.update_attributes(auth_token: token, user_id: id)
    else
      user_auth = AuthenticationToken.create!(auth_token: token, user_id: id)
    end
    binding.pry
    user_auth
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/timings_helper.rb
module TimingsHelper
end

app/views/layouts/adminlayout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Picnic Info</title>
  <%= stylesheet_link_tag	'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-top navbar-fixed-top">
    <div class="container-fluid">
      <div class="container">
        <div class="navbar-header">
   	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
   	        <span class="sr-only">Toggle navigation</span>
   	        <span class="icon-bar"></span>
   	        <span class="icon-bar"></span>
   	        <span class="icon-bar"></span>
   	      </button>
   	      <a class="navbar-brand" href="/">Picnic Info</a>
   	    </div>

      <div id="navbar" class="navbar-collapse collapse">
  		  <ul class="nav navbar-nav">
    		  <li class="dropdown">
      		  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">States <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "List", states_path %></li>
        			  <li><%= link_to "New", new_state_path %></li>
      			  </ul>
    		  </li>
  		  </ul>

        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Address <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "List", addresses_path %></li>
              </ul>
          </li>
        </ul>

  		  <ul class="nav navbar-nav">
    		  <li class="dropdown">
      		  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Place <span class="caret"></span></a>
      			  <ul class="dropdown-menu">
        			  <li><%= link_to "List", places_path %></li>
        			  <li><%= link_to "New", new_place_path %></li>
      			  </ul>
    		  </li>
  		  </ul>

        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ticket <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "List", tickets_path %></li>
              <li><%= link_to "New", new_ticket_path %></li>
            </ul>
          </li>
        </ul>

        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Timing <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "List", timings_path %></li>
                <li><%= link_to "New", new_timing_path %></li>
              </ul>
          </li>
        </ul>
        
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Picture <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "List", pictures_path %></li>
                <li><%= link_to "New", new_picture_path %></li>
              </ul>
          </li>
        </ul>


        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <% if user_signed_in? %>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= current_user.username %> <span class="caret"></span></a>
            <% end %>
              <ul class="dropdown-menu">
                <% if user_signed_in? %>
                  <li><%= link_to "Edit profile", edit_user_registration_path %></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                <% end %>
              </ul>
          </li>
        </ul>

      </div>
      </div>
    </div>
  </nav>
  
<div id="main-container" class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Picnic Info</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-top navbar-fixed-top">
    <div class="container-fluid">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><b>Picnic Info</b></a>
        </div>
        <div>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Login <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% if user_signed_in? %>
                  <li><%= link_to "Edit profile", edit_user_registration_path %></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                <% else %>
                  <li><%= link_to "Sign up", new_user_registration_path %></li>
                  <li><%= link_to "Login", new_user_session_path %></li>
                <% end %>
                
              </ul>
            </li>
          </ul>
        </div>
  </nav>
  
<div id="main-container" class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/staticpagelayout.html.erb
<%= flash_messages %>
<!DOCTYPE html>
<html>
<head>
  <title>Picnic Info</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
<link rel="stylesheet" type="text/css" href="staticpage.scss">
</style>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-top navbar-fixed-top">
    <div class="container-fluid">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Picnic Info</a>
        </div>
        <div>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <% if user_signed_in? %>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= current_user.username %>  <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Edit profile", edit_user_registration_path %></li>
                    <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                  </ul>
              <% else %>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Login  <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Sign up", new_user_registration_path %></li>
                    <li><%= link_to "Login", new_user_session_path %></li>
                  </ul>
              <% end %>
              
            </li>
          </ul>
        </div>
  </nav>
 


<div id="main-container" class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/pages/new.html.erb
<h2>Welcome to admin Panel...!</h2>